#!/usr/bin/env node
/**
 * Single source: public/game/manifest.json. Validates that every file under public/game/ has a
 * manifest row and every row's files exist (PLAN.md §5.6). Without --check, also (re)writes
 * CREDITS.md in TASL format, grouped by license.
 *
 * Usage: node tools/gen-credits.mjs [--check] [--release]
 * --check: validate only, exit non-zero on failure, do not write CREDITS.md.
 * --release: additionally fail on any manifest row with placeholder:true (the M6 gate).
 */

import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const gameDir = path.join(repoRoot, 'public/game');
const manifestPath = path.join(gameDir, 'manifest.json');

const args = process.argv.slice(2);
const checkOnly = args.includes('--check');
const releaseMode = args.includes('--release');

function walk(dir, out = []) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

if (!existsSync(manifestPath)) {
  console.error(`Missing ${manifestPath}`);
  process.exit(1);
}

const manifest = JSON.parse(readFileSync(manifestPath, 'utf-8'));
const errors = [];

const referencedFiles = new Set();
for (const asset of manifest.assets) {
  for (const relFile of asset.files) {
    const absFile = path.join(repoRoot, 'public', relFile);
    referencedFiles.add(path.resolve(absFile));
    if (!existsSync(absFile)) {
      errors.push(`Manifest entry "${asset.id}" references missing file: ${relFile}`);
    }
  }
  if (releaseMode && asset.placeholder) {
    errors.push(`Manifest entry "${asset.id}" is still a placeholder (not allowed at release)`);
  }
}

const allFiles = walk(gameDir).filter((f) => path.resolve(f) !== path.resolve(manifestPath));
for (const file of allFiles) {
  if (!referencedFiles.has(path.resolve(file))) {
    errors.push(`File has no manifest entry: ${path.relative(repoRoot, file)}`);
  }
}

if (errors.length > 0) {
  console.error('Asset manifest check failed:');
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

console.log(`Asset manifest OK: ${manifest.assets.length} entr${manifest.assets.length === 1 ? 'y' : 'ies'}, ${allFiles.length} file(s).`);

if (checkOnly) process.exit(0);

// --- Regenerate CREDITS.md, grouped by license (TASL: Title, Author, Source, License) ---------

const byLicense = new Map();
for (const asset of manifest.assets) {
  const license = asset.license.license || 'Unknown';
  if (!byLicense.has(license)) byLicense.set(license, []);
  byLicense.get(license).push(asset);
}

let out = '# Credits\n\n';
out += 'Generated by `tools/gen-credits.mjs` from `public/game/manifest.json`. Do not edit by hand.\n\n';
out += 'Seeonee is based on Rudyard Kipling\'s public-domain Mowgli stories (1894-95). Not affiliated with, endorsed by or sponsored by The Walt Disney Company or the 1994 Virgin Interactive game.\n\n';

for (const [license, assets] of byLicense) {
  out += `## ${license}\n\n`;
  for (const asset of assets) {
    const l = asset.license;
    out += `- **${l.title}** by ${l.author}${l.source ? ` (${l.source})` : ''}${l.modified ? ` — ${l.modified}` : ''}${l.aiAssisted ? ' [AI-assisted base]' : ''}\n`;
  }
  out += '\n';
}

out += '## Code\n\nSee `dist/licenses.txt` (generated by rollup-plugin-license on every build) for code dependency notices, including the Phaser MIT license.\n';

writeFileSync(path.join(repoRoot, 'CREDITS.md'), out);
console.log('Wrote CREDITS.md');
